almed|healthy, well|healthy||
amegre|temperature of|temperature_of|ameme|
ameme|ambient temperature|temperature||
awelme|something, someone|something||
awilma|everything, all|everything||
awolma|what|what||Putting this into a sentence turns it into a question
balas|laugh^the laugher|laugh||
bedre|hand of|hand_of|besegre|
bedrete|warm|warm||Refers to temperatures between 20°C and 30°C
beleti|scorching hot|hot||Refers to temperatures above 40°C
beleta|stove, oven, cooking heat source|stove|beleti|
belime|wind|wind|bet,gelume|
bemesh|feel, perceive^the one perceiving^the object being perceived|feel||Does not have to refer to touching, but any sense of "getting a feeling of"
benita|hot|hot||Refers to temperatures between 30°C and 40°C
berit|bite^the one biting^the object being bitten|bite|buvlit|
beroke|brisk, cool|brisk||Refers to temperatures between 10°C and 20°C
besedre|relative of|relative||Refers to anyone in the family who does not have another more specific kinship term
besegre|tool for...|tool||Refers to a tool for performing an action
beselet|sweep^sweeper^object/substance being swept off|sweep||
besope|foul, stinky, bad-smelling|foul||
bet|move^the mover^the moved object|move||
bevat|converse with, talk with^one of the speakers^the other of the speakers|converse|bevidre|
bevidre|voice of|voice|buvidre|
bileti|sharp|sharp||Refers to something that can cut; does not refer to smell or figurative meanings
bilepe|chisel|chisel|bilesop|
bilesop|carve^carver^object that is taking shape^material that is carved on|carve|bileti|
bimiki|angry|angry||
bimigre|anger, wrath, rage of|anger|bimiki|
binip|weave, plait^weaver^object being formed from the weaving^material used for the weaving|weave||
bodogre|beard of, mustache of|beard_of|bomodre,dolidre|
bodre|father of|father||
bolta|door|door||Both sides are inside a building
bomodre|chin of|chin_of||
bomol|sometimes, occassionally|sometimes||Used to modify verb infinitives to indicate a repeating action that happens sometimes
bores|breathe^the breather|breathe|borope|
borop|blow on^the blower^the object being blown on^the gas used|blow on||
borope|breath|breath|borop|
bota|nail|nail||
breta|male|male||
brepe|boy|breta||
brete|man|man|breta,tate|
bretodre|son of|son||
bulit|drink^the drinker^the liquid being drunk|drink|buvidre|
bup|speak, say^the speaker^the thing being said^the listener|say|buvidre|
buplit|spit^the spitter^the object spat out|spit|buvidre|
buridre|tongue of|tongue_of|buvidre|Refers to the organ, not languages
burit|lick^the licker^the object being licked|lick|buridre|
buvidre|mouth of|mouth||
buvlit|eat^the eater^the object being eaten|eat|buvidre|
dal|at the time of, when|at_time||
dedre|moment of|moment||Used to denote "when ..." or "at the moment when ..."
delegre|mood, emontional state of|mood|demeta,leved|
delit|tie together^the one performing the tying^first object being tied|tie||
delodre|back of|back_of||
delta|spot, dot, speck|spot||
demeta|joyful, glad, happy|happy||
demis|play, have fun^play, have fun|play|demeta|
dolidre|hair of|hair_of||Refers to any body hair
domote|house|house||Refers to any kind of dwelling place
drelote|rough, uneven|rough||
dulete|glass|glass|duna|
dumbete|clock, timepiece|clock|duna,bet|
duna|sand (substance)|sand||
dunagre|age|age|duna|Refers to the duration for which something has existed
duname|time|time|duna|Refers to the concept of time (i.e. arrow of time) itself
dutup|mold^one performing the molding^object being molded^material used for molding|mold||
edre|face of|face||
elata|new, novel|new|elita|Refers to something that one previously did not know (i.e. a new book = a book that one just obtained)
elita|new, young, recent|new||Refers to something that has not existed for too long (i.e. a new book = a book that was recently published)
emalip|return, come back^the one returning^the object being returned^the origin of the returned object|return||The reflexive form refers to returning or going back to the origin, which, if omitted, is presumably a place close to home or the speaker (if the speaker is not the one returning)
emelet|have a fear for^the one who has the fear^the thing that is feared|fear|emovet|
emika|I (singular), we (plural); first-person pronoun|FIRST_PERSON||
emodre|worry, concern of|worry|emovet|The associated word is the one having the worry
emolka|garden|garden||
emovet|worry about^the one worrying^the matter being worried about|worry||
enet|enchain, enshackle^the one performing the chaining^the one being chained up|enchain||
enote|chain, shackle|chain|enet|
eprat|touch^one of the touchers^the other of the touchers|touch||
epret|touch^the one initiating the touch^the one being touched|touch||
eradre|mistake, error made by|mistake||
erash|go to^the goer^the destination|go||
esika|you; second-person pronoun|SECOND_PERSON||
etika|he, she, it, they; third-person pronoun|THIRD_PERSON||
gedre|mother of|mother||
gelidre|(daily) life of|life_of|gelume,melidre|
gelish|live, dwell at^the person living^the location|live_at|gelidre|Refers to residing at a place
gelume|air|air||
ginedre|jaw of|jaw_of||
ginid|cool, refreshingly cold|cool||Related to "kenid" (cold), but refers to a temperature that one would enjoy
gladre|arm of|arm_of||Refers to the limb
glined|weak|weak||Refers to physical weakness
glodre|shoulder of|shoulder_of|gladre|
goled|quiet|quiet||Refers to sound pressure levels between 30 dB and 50 dB
goriv|be proud of^the one being proud^the one being proud of|proud||
gredre|leg of|leg_of||
grelet|embrace^the one embracing^the one being embraced|embrace||
grema|world|world|gremi,vosma|
gremegre|soul, spirit of|soul|grema|
gremi|sky|sky||
gremune|weather|weather|gremi|Refers to the state of the sky at a given time
gremute|weather condition|weather|gremune|Refers to any of the weather conditions, such as rain, sun, etc.
gresigre|roof of|roof_of||gremu
grid|female|female||
grike|girl|grid||
grite|woman|woman|grid,tate|
gritodre|daughter of|daughter||
gromod|frequent, recurring|frequent||
grumid|bitter|bitter||
hem|I|I|emika|Functionally identical to "emikasi"
hes|you (singular)|you|esika|Functionally identical to "esikasi"
het|he, she, it; third-person singular pronoun|3PS|etika|Functionally identical to "etikasi"
hime|We|We|emika|Functionally identical to "emikave"
hise|you (plural)|you|esika|Functionally identical to "esikave"
hite|they|3PP|etika|Functionally identical to "each other"
idogre|poison to...|poison||
ilesh|faithful, loyal to^the one being faithful^the one being faithful to|faithful||Does not refer to religion
imilta|room|room||
ireg|cough^the one coughing|cough||
kanedre|wave of|wave||
kanel|capably, skillfully|capably||When modifying a verb infinitive, it corresponds to "can" or "be able to"
kebedre|head of (body)|head_of||Cannot be used figuratively
kebot|break (shatter)^breaker^object that is shattered|break||Used to denote that the object shatters into small pieces
kedred|cold|cold||Refers to temperatures between -20°C and 0°C
keled|lively loud|lively||Refers to sound pressure levels between 50 dB and 70 dB
keledrid|extremely cold|cold||Refers to temperatures below -40°C
kemedre|neck of|neck_of|kebedre|
kened|loud|loud||Refers to sound pressure levels between 70 dB and 100 dB
kenid|uncomfortably cold|cold||Subjectively defined; refers to any temperature that is painful to endure
kenidred|unbearably cold|cold||Refers to temperatures between -40°C and -20°C
kesig|sneeze^the one sneezing|sneeze||
kete|sound|sound||Refers to any instance of sound
keted|extremely loud|loud||Refers to sound pressure levels between 100 dB and 150 dB
kirid|brave, courageous|brave||
kirigre|bravery, courage of|bravery|kirid|
kiriki|danger, dangerous situation|danger|kirid|
kirish|dare, have the bravery to...^dare, have the bravery to...^dare|dare|kirid|
kitrot|make, build, construct, create^maker^object that is created|make||
kivat|cook^the cook^the dish or food being made|cook||
klested|deafeningly loud|loud||Refers to sound pressure levels above and including 150 dB
kliti|key (lock)|key||Refers to the tool used open a lock
kluti|lock|lock|kliti|
konal|another, other|another||
kregre|color of, colour of|colour_of|krete|Followed by an object with a characteristic colour to denote that colour
krelni|shade,shadow|shadow|krene,lini|
krena|dawn, daybreak|dawn|krenit|
krene|light|light||Refers to visible light
krenit|light up, illuminate^light up, illuminate^illuminate|illuminate|krene|
krenod|bright|bright|krene|Refers to an abundance of light
krenti|window|window|krene|
kresite|ceiling light|light|krene|
kreska|candle|candle|kreska|
kreskene|lightning|lightning|kresne,krene|
kreski|flame|flame|poski,krene|Refers to the light emitted by fire
kresne|thunder|thunder||
kresnod|thunderous|thunderous|kresne|
kreste|lamp, flashlight, torch, localized lighting|lamp|krene|
krete|color, colour|colour|krene|Refers to the concept of colours in general, not to any specific colour
kulete|river|river|leres,kuna|
kumol|today|today|kumome|Stands for "dal kumome"
kumome|today|today||
kuna|water|water||
kunad|wet, damp|wet|kunad|
kunapa|spring, well|well|kuna|
kunata|ocean,sea|ocean|kuna|
kunep|pour^one performing the pouring^object/substance being poured^receptacle of poured object/substance|pour|kuna|
kunerash|swim^the swimmer^the destination|swim|kuna,erash|
kunidre|breast of, chest of|chest_of||
kunod|hard, firm|hard||Refers to physical hardness, not difficulty
kuvosta|lake|lake|kuna,vosma|
larep|show^the one showingr^the viewer^the object being shown|show|liresh|
lemid|sorry, regrettable|regrettable|lemiv|Not used for apologies, which uses "lomov" instead
lemiv|pity, feel sorry for^the one who is pitying^the one being pitied|lemed||
leredre|current of, flow of|flow|leres|
leres|flow^the substance that flows|flow||
leris|rest, take a break^the one resting|rest||
leved|sad|sad||
levegre|grief, sorrow, sadness of|sadness|levegre|
lidre|edge of|edge||
likuta|shore|shore|lidre,kunata|
limid|pure|pure||
lined|peacefully quiet|quiet||Refers to quietness that is peaceful
lini|darkness|darkness|linud|
linud|black|black||
lipid|tired, weary, exhausted|tired||
lipoti|chair|chair||
liredre|eye of|eye||
lirekuta|tear (from the eyes)|tear|liredre,kuna|
liresh|look at^the one looking^the one being looked at|look at|liredre|
lirish|watch, stare at^the one watching^the one being stared at|watch|liresh|
lisip|cut^cutter^object being cut^cutting tool|cut||Specialized words exist for cutting with scissors, knife, and axe
lite|nighttime, night|night||
liteneg|die^the one dying|die|lite|
liveras|sleep, especially through the night^the sleeper|sleep||
liveti|bed|bed|liveras|
lomed|light (weight)|light|lomid|Refers to an object whose weight makes it easy to handle
lomid|light, lightweight|light||Refers to an object whose weight is below what is expected
lomov|be sorry about, regret^the one regretting^the matter being regretted about|regret|lemiv|
lukregre|body of|body_of||
lukrene|sunrise|sunrise|luna,krene|
lukuna|blood|blood|lukregre,kuna|
lumid|beautiful|beautiful||
luna|sun|sun||Specifically refers to the star that the Earth orbits
lunata|star|star|luna|Refers to the astronomical objects
lunome|summer|summer|luna|
lurika|cloud|cloud||
lutreta|bone|bone|lukregre,treta|
luvem|rain (weather condition)|rain||
luvema|rain (substance)|rain|luvem|Refers to the falling rain itself
mamod|lazy|lazy||
marodre|aunt of, uncle of|aunt/uncle||
mebeta|gate|gate||At least one side is outside of a building
meki|tree|tree||
mel|in, within (abstract)|in||Used to describe being within a timeframe or environment, such as "in the night", "in a week"
meledre|stomach of|stomach_of||
melidre|life (state) of|life_of|melis|
melis|breathe^the one who breathes|melidro||
melmote|yard, court|yard||
memeki|forest,woods|forest|melidre,meki|
memi|wood (substance)|wood|meki|
memid|fragrant, good smelling, sweet|fragrant||
memome|yesterday|yesterday|meveme,kumome|
menedre|belly of|belly_of||
mepogre|finger of, toe of|finger_of||
meral|but, however|but||
meranip|sculpt^sculptor^object that results from sculpting^material used for sculpting|sculpt||Refers to a fine and often tedious means of creating something out of a raw material
mered|warm, hot, cozy|warm||Refers to a comfortably warm temperature
merke|hour|hour||
merli|hour (duration)|hour|merke|
merome|collection of memories|memories|meveme|Refers to the entire collection of memories that a person holds
merope|piece of memory|memory|merome|Refers to a single remembered event
mesip|become, transform into^the one transforming^the one being transformed^the new form|become||Use the reflexive form to denote "become"
mesote|autumn, fall|autumn||
meta|space, area|area||
metodre|nose of|nose_of|metosh|
metogre|scent of, smell of|scent_of||
metosh|smell^the smeller^the object being smelled|smell|metogre|
meveme|past|past|meves|
meves|look back^the one looking back|look back||Refers to either physically turning around and looking, or reflecting about the past
mika|day (entire)|day||Refers to the twenty-four-hour period
mikali|day (duration)|day|mika|
minaka|daytime|daytime||Refers to the period between dawn and dusk
mirabat|kiss on the lips^one of the kissers^the other of the kissers|kiss|mirav,buvidre|
mirabut|kiss^the kisser^the one being kissed|kiss|mirav,buvidre|
miradre|significant other, soulmate|soulmate|mirav|Marriage does not change this usage of terms
mirav|love romantically^one of the lovers^the other of the lovers|love||
mirev|love, have feelings for^the one having the feelings^the one who is loved|love|mirav|Used to denote a person's feelings whether it's reciprocated or not
mogal|tomorrow|tomorrow|morgome|Stands for "dal morgome"
morgome|tomorrow|tomorrow||
moridre|brain of|brain_of||
morodre|ancestor of|ancestor|moromi|
moromi|ancestors, ancestry|ancestry||
moropa|rope|rope||
morot|spread out^one performing the spreading out^substance being spreaded out|spread||
mumod|smooth, even|smooth||
nal|with the name of|named||The following word is the name of the modified object
narish|run^the runner^the destination|run||
nebud|dirty|dirty||Does not have to be covered in dirt, but anything that is undesirable
negre|interior of|interior||
nel|in (unbound space or time)|in||Used to denote "in the night", "in the decade", etc.
nelegre|year of|year|nelelte|Refers to a named, specific year
neleli|year (duration)|year|nelelte|
nelelte|year|year||
nelite|season|season||
nelpe|basket|basket||
nelvidre|cheek of|cheek_of||Refers to facial cheek
nemite|person who has lost a loved one|love-lost person||Specifically refers to a person whose love with a siginificant other (miradre); cannot be used like the term "widow"
nepidre|throat of|throat_of||Refers to the body part only
nerid|cool|cool||Refers to temperatures between 0°C and 10°C
nerig|cry, weep^cry, weep|cry||
nesegre|elbow of, knee of, joint of|joint_of||
nitrosh|read^the reader^the text or document being read|read||
nival|other than, not|not||Used to mean "something other than", which is sometimes indicated with negation in natural languages
nolod|bad, disagreeable, not likeable|bad||
nolop|blame^the one performing the blaming^the one being blamed^the matter being blamed for|blame|nolod|
nomal|always, regularly|always||When modifying an infinitive, indicates that the action occurs regularly; when modifying an ongoing action (either progressive or also having "tenil" attached to it), indicates that the action will not stop
nonte|table, desk|table||
numod|bored|bored||
olad|old, already familiar|old|olid|Refers to expressions like "old news" or "old trick"
olid|old, existed for a long time|old||Can refer to both objects and humans
olud|old, near the end of lifespan|old|olid|Can refer to both objects and humans
omod|silent|silent||Refers to sound pressure levels below 30 dB
peledre|descendant of|descendant|morodre|
pemed|heavy|heavy|pemid|Refers to an object whose weight makes it difficult to handle
pemid|heavy, heavyweight|heavy||Refers to an object whose weight is above what is expected
petrogre|taste of|taste_of|petrot|
petrot|taste^the taster^the object being tasted|taste||
pinuni|medicine, drug|medicine|pinut|
pinut|heal, cure^the healer^the one being healed|heal||
pived|sour|sour||
podad|dry|dry||Refers to an absence of moisture
pogre|flesh of, meat of|flesh_of||Used only to describe animals and fruits
polov|hate^the hater^the one being hated|hate||
pomupa|valley|temitaa||
popid|ugly|ugly||
porip|write^the writer^the text being written^the medium written on|write||
porodre|wound, painpoint of|wound_of||May be used figuratively, depending on its associated class
posip|pull, draw^one performing the pulling^object being pulled^tesip|pull|tesip|
poski|fire|fire||
poskut|burn^the one igniting the object^the burned object|burn|poski|To denote that something is "on fire", use the reduced form "poskig"
potid|strong, mighty, powerful, forceful|strong||
prelig|be ready, idling, waiting^the one who is ready|ready||
pretid|annoyingly loud|loud||Refers to loudness that causes discomfort
pulte|wall|wall||
ralud|soft, malleable|soft||
rebot|cut (with scissors)^cutter^object being cut|cut|repete|
regel|soon|soon|regel|
relite|evening|evening|renel,relite|
remigre|human head hair of|hair_of||
remika|morning|morning|renel,mika|
rened|clean|clean||Refers to physical cleaniness; for figurative cleaniness, use "lemid" (pure)
renel|early|early||Modifies a stopped verb to indicate that it finished before the expected time
renod|early in the day|early||
repete|scissors|scissors||
resip|paint^painter^object being painted^colour/material/texture being painted into|paint||
retigre|skin of|skin_of||
revita|dream|dream||Refers to visions seen while sleeping
ridre|vicinity of|vicinity_of||Denotes "around <object>"
rilep|wash^washer^object being washed^substance (e.g. water) used for the washing|wash||
rima|moon (of Earth)|moon||
rimata|moon (natural satellite)|rimaa||
rimogre|month of|month|rimpe|Followed by a number to denote a specific month
rimpe|month|month|rima|
rinome|winter|winter|rima|
risme|smoke|smoke||
ritma|ash|ash||Specifically refers to the residue of burning
romod|eerily quiet|quiet||Refers to unexpected quietness that causes anxiety
rote|plain, field, open area|field||
rotopi|illness, sickness, disease|illness||
runata|dream, wish, ideal, goal|goal||Refers to a hypothetical reality that one wishes to bring to reality
sebot|break (split)^breaker^object that is broken|break|kebot|Used to denote that the object is broken into large, usually two, pieces
semagre|week of|week|sempa|Refers to a named, specific week
semali|week (duration)|week|sempa|
sempa|week|week||
sered|good, likeable, agreeable|good|serev|
serev|like, be fond of^the one who likes^the one who is liked|like||Can refer to both people and things; when used on people, suggests platonic fondness
seskad|solid|solid||Refers to the solid state of matter
seskom|snow (weather condition)|snow|seskuna|
seskoma|snow (substance)|snow||Refers to the snow itself, as opposed to the weather
seskuna|ice|ice|seskad,kuna|
set|want, desire, wish^the one who has a desire^the desired thing|want||Can be used as an alternative to the volition inflection if the act of wishing itself needs a description
sibed|hasty, hurried|hasty|sibed|
sibit|hurry, rush^the one hurrying^the action being hurried|hurry||To say "rushed to <destination>", use "erash sibedea", which means "hastily go to"
sinedre|heart of|heart_of||
sinip|rub, wipe^one performing the rubbing^object being rubbed^tool used to rub/substance being rubbed|rub||
sirid|fast, rapid, quick|fast||
sirit|rip, tear^rip, tear^rip|rip||
soki|knife, blade|knife||
sokut|cut (with knife)^cutter^object being cut|cut|soki|
sonal|only|only||
sonol|without, lacking|without||Used to modify an object that lacks an association, either through ownership or characteristic, with the following object
soponi|pain|pain|soki,poski|
sorod|slow|slow||
sud|wrong|wrong|vid|antonym of vid
tate|adult|adult|tote|
tatrete|person|person||May refer to both adults and children
temita|mountain, hill|mountain||
tenet|fill, take up space, flood with^the filling substance^the container being filled|fill|tenip|Use "tenip" to denote that the filling agent is not the substance used to fill the container
tenil|currently|currently||Can be used to modify verb infinitives or other forms to indicate the ongoing state of the action
tenip|fill^the one performing the filling^the container being filled^the substance used to fill the container|fill||Use "tenet" to denote that the substance is also the one performing the filling
tesip|press, push, compress^one performing the pressing^object being pressed^surface being pressed against|push||Can also mean "push ... towards ..."
tilit|cut, chop (with axe)^cutter^object being chopped|chop|tilte|
tilte|axe|axe||
tired|uncomfortably hot|hot||Subjectively defined; refers to a temperature that causes discomfort
titolit|kill^the killer^the victim|kill||
todre|child (offspring) of|child|tote|
togedre|tail of|tail_of|tokigre|
tokigre|butt of, buttocks of|butt_of||
tokol|late, near the end of a period of time|late||
tomol|late|late||Refers to an action occuring after the expected time
tomop|postpone, delay^the one postponing^the event being postponed^the time postponed to|postpone||
tosete|hammer|hammer||
tot|hit, strike, beat^hitter^object being hit|hit||
tote|child|child||
tregre|end of|end|trelot|Indicates the end of an action or a period (e.g. season or day)
trelit|begin, start^the one starting an action^the action being started|begin||The slot-2 argument should be a verb in the occurrence inflection; has the same semantics as the transitive/initiation action, so it's used when the initiation itself needs a modifier
trelot|finish, complete^the one finishing up^the action being completed|finish||
trena|stone (substance)|stone||
trenata|statue|statue|trena|
treta|rock|rock|trena|
treted|pleasantly loud|loud||Refers to loudness that is pleasant
trigre|start, beginning of|beginning|trelit|
trolot|stop^the one stopping^the action that is stopped|stop||Does not imply "finish" or "complete", which is handled by "orit"
venedre|sibling of|sibling||
veneme|spring|spring||
veredre|ear of|ear||
veresh|listen to, hear^the listener^the sound being heard|hear|veredre|
vid|correct, right|correct||Used to describe something that conforms to a standard
vidre|lip of|lip_of|buvidre|
vilipi|broom|broom|vilme|
vilme|dust|dust||Refers to any fine-grained particles, including ash
vilot|bend^bender^object that is bent|bend||
vogodre|tooth of|tooth_of||Usually refers to a person's complete set of teeth, unless specified using the singular inflection
vogre|midpoint of|midpoint||
vol|of, pertaining to|of||Links two objects without explicitly stating the nature of the relationship, which is left to the context to decide
voline|midnight, dark night|midnight|vogre,lite|Refers to the time of the day when dusk and dawn are equidistant; to refer to 00:00, use "trigre mika" (beginning of day) instead
volune|solar noon|noon|vogre,luna|Refers to the time of the day when the sun is at the zenith; to refer to 12:00, use "vogro mika" (middle of the day) instead
vome|soil|soil|vosma|
vomot|wake up, awaken^the waker^the one waking up|wake_up||Use the reflexive inflection to indicate naturally waking oneself up
vosedre|foot of, paw of|foot_of||Refers to any body part that normally touches the ground
vosip|bury^the one burying^the object being buried^the location of the burial|bury|vosma|
vosma|earth, ground|earth||Refers to the ground, not the planet
vosmi|floor|floor|vosma|Refers to any kind of indoor ground, not just wooden floor
vosnata|bay, gulf|bay|vosma,kunata|
vososit|fold^one performing the folding^object being folded|fold||
vosrima|fog,mist|fog|vosma,lurika|
vulot|stretch^stretch^stretch|stretch||
wel|something, someone|something|awelme|Functionally identical to "awelme"
wil|everything, all|everything|awilma|Functionally identical to "awilma"
wol|what|what|awolma|Functionally identical to "awolma"
