almed|healthy, well|healthy||
amegro|temperature of|temperature_of|amemo|
amemo|ambient temperature|temperature||
awelmo|something, someone|something||
awilmaa|everything, all|everything||
awolmaa|what|what||Putting this into a sentence turns it into a question
balag|laugh^the laugher|laugh||
bedred|warm|warm||Refers to temperatures between 20°C and 30°C
bedro|hand of|hand_of|besegro|
beledrid|scorching hot|hot||Refers to temperatures above 40°C
belimo|wind|wind|bet,gelumo|
bemesh|feel, perceive^the one perceiving^the object being perceived|feel||Does not have to refer to touching, but any sense of "getting a feeling of"
benidred|hot|hot||Refers to temperatures between 30°C and 40°C
berit|bite^the one biting^the object being bitten|bite|buvlit|
berod|brisk, cool|brisk||Refers to temperatures between 10°C and 20°C
besedro|relative of|relative||Refers to anyone in the family who does not have another more specific kinship term
besegro|tool for...|tool||Refers to a tool for performing an action
beselet|sweep^sweeper^object/substance being swept off^surface being swept|sweep||
besod|foul, stinky, bad-smelling|foul||
bet|move^the mover^the moved object|move||
bevat|converse with, talk with^one of the speakers^the other of the speakers|converse|bevidro|
bevidro|voice of|voice|buvidro|
biled|sharp|sharp||Refers to something that can cut; does not refer to smell or figurative meanings
bilepo|chisel|chisel|bilesop|
bilesop|carve^carver^object that is taking shape^material that is carved on|carve|biled|
bimid|angry|angry||
bimigro|anger, wrath, rage of|anger|bimid|
binip|weave, plait^weaver^object being formed from the weaving^material used for the weaving|weave||
bodogro|beard of, mustache of|beard_of|bomodro,dolidro|
bodro|father of|father||
bomodro|chin of|chin_of||
bomol|sometimes, occassionally|sometimes||Used to modify verb infinitives to indicate a repeating action that happens sometimes
bores|breathe^the breather|breathe|boropo|
borop|blow on^the blower^the object being blown on^the gas used|blow on||
boropo|breath|breath|borop|
botaa|nail|nail||
bred|male|male||
brepo|boy|bred||
breto|man|man|bred,tato|
bretodro|son of|son||
bulit|drink^the drinker^the liquid being drunk|drink|buvidro|
bup|speak, say^the speaker^the thing being said^the listener|say|buvidro|
buplit|spit^the spitter^the object spat out|spit|buvidro|
buridro|tongue of|tongue_of|buvidro|Refers to the organ, not languages
burit|lick^the licker^the object being licked|lick|buridro|
buvidro|mouth of|mouth||
buvlit|eat^the eater^the object being eaten|eat|buvidro|
dal|at the time of, when|at_time||
dedro|moment of|moment||Used to denote "when ..." or "at the moment when ..."
delegro|mood, emontional state of|mood|demed,leved|
delit|tie together^the one performing the tying^first object being tied^second and rest of the objects being tied|tie||
delodro|back of|back_of||
demed|joyful, glad, happy|happy||
demis|play, have fun^play, have fun|play|demed|
dolidro|hair of|hair_of||Refers to any body hair
drelod|rough, uneven|rough||
duleto|glass|glass|dunaa|
dumbeto|clock, timepiece|clock|dunaa,bet|
dunaa|sand (substance)|sand||
dunagro|age|age|dunaa|Refers to the duration for which something has existed
dunamo|time|time|dunaa|Refers to the concept of time (i.e. arrow of time) itself
dutup|mold^one performing the molding^object being molded^material used for molding|mold||
edro|face of|face||
elad|new, novel|new|elid|Refers to something that one previously did not know (i.e. a new book = a book that one just obtained)
elid|new, young, recent|new||Refers to something that has not existed for too long (i.e. a new book = a book that was recently published)
emalip|return, come back^the one returning^the object being returned^the origin of the returned object|return||The reflexive form refers to returning or going back to the origin, which, if omitted, is presumably a place close to home or the speaker (if the speaker is not the one returning)
emelev|have a fear for^the one who has the fear^the thing that is feared|fear|emonev|
emikaa|I (singular), we (plural); first-person pronoun|FIRST_PERSON||
emodro|worry, concern of|worry|emonev|The associated word is the one having the worry
emonev|worry about^the one worrying^the matter being worried about|worry||
enet|enchain, enshackle^the one performing the chaining^the one being chained up|enchain||
enoto|chain, shackle|chain|enet|
eprat|touch^one of the touchers^the other of the touchers|touch||
epret|touch^the one initiating the touch^the one being touched|touch||
eradro|mistake, error made by|mistake||
erash|go to^the goer^the destination|go||
esikaa|you; second-person pronoun|SECOND_PERSON||
etikaa|he, she, it, they; third-person pronoun|THIRD_PERSON||
gedro|mother of|mother||
gelidro|(daily) life of|life_of|gelumo,melidro|
gelumo|air|air||
ginedro|jaw of|jaw_of||
ginid|cool, refreshingly cold|cool||Related to "kenid" (cold), but refers to a temperature that one would enjoy
gladro|arm of|arm_of||Refers to the limb
glined|weak|weak||Refers to physical weakness
glodro|shoulder of|shoulder_of|gladro|
goled|quiet|quiet||Refers to sound pressure levels between 30 dB and 50 dB
goriv|be proud of^the one being proud^the one being proud of|proud||
gredro|leg of|leg_of||
grelet|embrace^the one embracing^the one being embraced|embrace||
gremaa|world|world|gremu,vosmaa|
gremegro|soul, spirit of|soul|gremaa|
gremu|sky|sky||
gremuno|weather|weather|gremu|Refers to the state of the sky at a given time
gremuto|weather condition|weather|gremuno|Refers to any of the weather conditions, such as rain, sun, etc.
grid|female|female||
griko|girl|grid||
grito|woman|woman|grid,tato|
gritodro|daughter of|daughter||
gromod|frequent, recurring|frequent||
grumid|bitter|bitter||
hem|I|I|emikaa|Functionally identical to "emikasi"
hes|you (singular)|you|esikaa|Functionally identical to "esikasi"
het|he, she, it; third-person singular pronoun|3PS|etikaa|Functionally identical to "etikasi"
hime|We|We|emikaa|Functionally identical to "emikave"
hise|you (plural)|you|esikaa|Functionally identical to "esikave"
hite|they|3PP|etikaa|Functionally identical to "each other"
idogro|poison to...|poison||
ilesh|faithful, loyal to^the one being faithful^the one being faithful to|faithful||Does not refer to religion
ireg|cough^the one coughing|cough||
kanedro|wave of|wave||
kanel|capably, skillfully|capably||When modifying a verb infinitive, it corresponds to "can" or "be able to"
kebedro|head of (body)|head_of||Cannot be used figuratively
kebot|break (shatter)^breaker^object that is shattered|break||Used to denote that the object shatters into small pieces
kedred|cold|cold||Refers to temperatures between -20°C and 0°C
keled|lively loud|lively||Refers to sound pressure levels between 50 dB and 70 dB
keledrid|extremely cold|cold||Refers to temperatures below -40°C
kemedro|neck of|neck_of|kebedro|
kened|loud|loud||Refers to sound pressure levels between 70 dB and 100 dB
kenid|uncomfortably cold|cold||Subjectively defined; refers to any temperature that is painful to endure
kenidred|unbearably cold|cold||Refers to temperatures between -40°C and -20°C
kesig|sneeze^the one sneezing|sneeze||
keted|extremely loud|loud||Refers to sound pressure levels between 100 dB and 150 dB
keto|sound|sound||Refers to any instance of sound
kirid|brave, courageous|brave||
kirigro|bravery, courage of|bravery|kirid|
kiriku|danger, dangerous situation|danger|kirid|
kirish|dare, have the bravery to...^dare, have the bravery to...^dare|dare|kirid|
kitrot|make, build, construct, create^maker^object that is created|make||
kivat|cook^the cook^the dish or food being made|cook||
klested|deafeningly loud|loud||Refers to sound pressure levels above and including 150 dB
kregro|color of, colour of|colour_of|kreto|Followed by an object with a characteristic colour to denote that colour
krelnu|shade,shadow|shadow|kreno,linu|
krenaa|dawn, daybreak|dawn|krenit|
krenit|light up, illuminate^light up, illuminate^illuminate|illuminate|kreno|
kreno|light|light||Refers to visible light
krenod|bright|bright|kreno|Refers to an abundance of light
kreskeno|lightning|lightning|kresno,kreno|
kresku|flame|flame|posku,kreno|Refers to the light emitted by fire
kresno|thunder|thunder||
kresnod|thunderous|thunderous|kresno|
kreto|color, colour|colour|kreno|Refers to the concept of colours in general, not to any specific colour
kuleto|river|river|leres,kunaa|
kumol|today|today|kumomo|Stands for "dal kumome"
kumomo|today|today||
kunaa|water|water||
kunad|wet, damp|wet|kunad|
kunapaa|spring, well|well|kunaa|
kunataa|ocean,sea|ocean|kunaa|
kunep|pour^one performing the pouring^object/substance being poured^receptacle of poured object/substance|pour|kunaa|
kunerash|swim^the swimmer^the destination|swim|kunaa,erash|
kunidro|breast of, chest of|chest_of||
kunod|hard, firm|hard||Refers to physical hardness, not difficulty
kuvostaa|lake|lake|kunaa,vosmaa|
larep|show^the one showingr^the viewer^the object being shown|show|liresh|
lemid|sorry, regrettable|regrettable|lemiv|Not used for apologies, which uses "lomov" instead
lemiv|pity, feel sorry for^the one who is pitying^the one being pitied|lemed||
leredro|current of, flow of|flow|leres|
leres|flow^the substance that flows|flow||
leris|rest, take a break^the one resting|rest||
leved|sad|sad||
levegro|grief, sorrow, sadness of|sadness|levegro|
lidro|edge of|edge||
likutaa|shore|shore|lidro,kunataa|
limid|pure|pure||
lined|peacefully quiet|quiet||Refers to quietness that is peaceful
linu|darkness|darkness|linud|
linud|black|black||
lipid|tired, weary, exhausted|tired||
liredro|eye of|eye||
lirekutaa|tear (from the eyes)|tear|liredro,kunaa|
liresh|look at^the one looking^the one being looked at|look at|liredro|
lirish|watch, stare at^the one watching^the one being stared at|watch|liresh|
lisip|cut^cutter^object being cut^cutting tool|cut||Specialized words exist for cutting with scissors, knife, and axe
liteneg|die^the one dying|die|lito|
lito|nighttime, night|night||
lomed|light (weight)|light|lomid|Refers to an object whose weight makes it easy to handle
lomid|light, lightweight|light||Refers to an object whose weight is below what is expected
lomov|be sorry about, regret^the one regretting^the matter being regretted about|regret|lemiv|
lukregro|body of|body_of||
lukreno|sunrise|sunrise|lunaa,kreno|
lukunaa|blood|blood|lukregro,kunaa|
lumid|beautiful|beautiful||
lunaa|sun|sun||Specifically refers to the star that the Earth orbits
lunataa|star|star|lunaa|Refers to the astronomical objects
lunomo|summer|summer|lunaa|
lurikaa|cloud|cloud||
lutretaa|bone|bone|lukregro,tretaa|
luvem|rain (weather condition)|rain||
luvemaa|rain (substance)|rain|luvem|Refers to the falling rain itself
mamod|lazy|lazy||
marodro|aunt of, uncle of|aunt/uncle||
meku|tree|tree||
meledro|stomach of|stomach_of||
melidro|life (state) of|life_of|melis|
melis|breathe^the one who breathes|melidro||
memeku|forest,woods|forest|melidro,meku|
memid|fragrant, good smelling, sweet|fragrant||
memomo|yesterday|yesterday|mevemo,kumomo|
memu|wood (substance)|wood|meku|
menedro|belly of|belly_of||
mepogro|finger of, toe of|finger_of||
meral|but, however|but||
meranip|sculpt^sculptor^object that results from sculpting^material used for sculpting|sculpt||Refers to a fine and often tedious means of creating something out of a raw material
mered|warm, hot, cozy|warm||Refers to a comfortably warm temperature
merko|hour|hour||
merli|hour (duration)|hour|merko|
meromo|collection of memories|memories|mevemo|Refers to the entire collection of memories that a person holds
meropo|piece of memory|memory|meromo|Refers to a single remembered event
mesip|become, transform into^the one transforming^the one being transformed^the new form|become||Use the reflexive form to denote "become"
mesoto|autumn, fall|autumn||
metaa|space, area|area||
metodro|nose of|nose_of|metosh|
metogro|scent of, smell of|scent_of||
metosh|smell^the smeller^the object being smelled|smell|metogro|
mevemo|past|past|meves|
meves|look back^the one looking back|look back||Refers to either physically turning around and looking, or reflecting about the past
mikaa|day (entire)|day||Refers to the twenty-four-hour period
mikali|day (duration)|day|mikaa|
minakaa|daytime|daytime||Refers to the period between dawn and dusk
mirabat|kiss on the lips^one of the kissers^the other of the kissers|kiss|mirav,buvidro|
mirabut|kiss^the kisser^the one being kissed|kiss|mirav,buvidro|
miradro|significant other, soulmate|soulmate|mirav|Marriage does not change this usage of terms
mirav|love romantically^one of the lovers^the other of the lovers|love||
mirev|love, have feelings for^the one having the feelings^the one who is loved|love|mirav|Used to denote a person's feelings whether it's reciprocated or not
mogal|tomorrow|tomorrow|morgomo|Stands for "dal morgome"
morgomo|tomorrow|tomorrow||
moridro|brain of|brain_of||
morodro|ancestor of|ancestor|moromu|
moromu|ancestors, ancestry|ancestry||
moropaa|rope|rope||
morot|spread out^one performing the spreading out^substance being spreaded out|spread||
mumod|smooth, even|smooth||
narish|run^the runner^the destination|run||
nebud|dirty|dirty||Does not have to be covered in dirt, but anything that is undesirable
negro|interior of|interior||
nel|in (unbound space or time)|in||Used to denote "in the night", "in the decade", etc.
nelegro|year of|year|nelelto|Refers to a named, specific year
neleli|year (duration)|year|nelelto|
nelelto|year|year||
nelito|season|season||
nelpo|basket|basket||
nelvidro|cheek of|cheek_of||Refers to facial cheek
nemito|person who has lost a loved one|love-lost person||Specifically refers to a person whose love with a siginificant other (miradre); cannot be used like the term "widow"
nepidro|throat of|throat_of||Refers to the body part only
nerid|cool|cool||Refers to temperatures between 0°C and 10°C
nerig|cry, weep^cry, weep|cry||
nesegro|elbow of, knee of, joint of|joint_of||
nitrosh|read^the reader^the text or document being read|read||
nival|other than, not|not||Used to mean "something other than", which is sometimes indicated with negation in natural languages
nolod|bad, disagreeable, not likeable|bad||
nolop|blame^the one performing the blaming^the one being blamed^the matter being blamed for|blame|nolod|
nomal|always, regularly|always||When modifying an infinitive, indicates that the action occurs regularly; when modifying an ongoing action (either progressive or also having "tenil" attached to it), indicates that the action will not stop
numod|bored|bored||
olad|old, already familiar|old|olid|Refers to expressions like "old news" or "old trick"
olid|old, existed for a long time|old||Can refer to both objects and humans
olud|old, near the end of lifespan|old|olid|Can refer to both objects and humans
omod|silent|silent||Refers to sound pressure levels below 30 dB
peledro|descendant of|descendant|morodro|
pemed|heavy|heavy|pemid|Refers to an object whose weight makes it difficult to handle
pemid|heavy, heavyweight|heavy||Refers to an object whose weight is above what is expected
petrogro|taste of|taste_of|petrot|
petrot|taste^the taster^the object being tasted|taste||
pinunu|medicine, drug|medicine|pinut|
pinut|heal, cure^the healer^the one being healed|heal||
pived|sour|sour||
podad|dry|dry||Refers to an absence of moisture
pogro|flesh of, meat of|flesh_of||Used only to describe animals and fruits
polov|hate^the hater^the one being hated|hate||
pomupaa|valley|temitaa||
popid|ugly|ugly||
porip|write^the writer^the text being written^the medium written on|write||
porodro|wound, painpoint of|wound_of||May be used figuratively, depending on its associated class
poskit|burn^the one igniting the object^the burned object|burn|posku|To denote that something is "on fire", use the reduced form "poskig"
posku|fire|fire||
potid|strong, mighty, powerful, forceful|strong||
posip|pull, draw^one performing the pulling^object being pulled^tesip|pull|tesip|
prelig|be ready, idling, waiting^the one who is ready|ready||
pretid|annoyingly loud|loud||Refers to loudness that causes discomfort
ralud|soft, malleable|soft||
rebot|cut (with scissors)^cutter^object being cut|cut|repeto|
regel|soon|soon|regel|
relito|evening|evening|renel,relito|
remigro|human head hair of|hair_of||
remikaa|morning|morning|renel,mikaa|
rened|clean|clean||Refers to physical cleaniness; for figurative cleaniness, use "lemid" (pure)
renel|early|early||Modifies a stopped verb to indicate that it finished before the expected time
renod|early in the day|early||
repeto|scissors|scissors||
resip|paint^painter^object being painted^colour/material/texture being painted into|paint||
retigro|skin of|skin_of||
revitaa|dream|dream||Refers to visions seen while sleeping
ridro|vicinity of|vicinity_of||Denotes "around <object>"
rimaa|moon (of Earth)|moon||
rimataa|moon (natural satellite)|rimaa||
rimogro|month of|month|rimpo|Followed by a number to denote a specific month
rimpo|month|month|rimaa|
rinomo|winter|winter|rimaa|
rismo|smoke|smoke||
ritmaa|ash|ash||Specifically refers to the residue of burning
rilep|wash^washer^object being washed^substance (e.g. water) used for the washing|wash||
romod|eerily quiet|quiet||Refers to unexpected quietness that causes anxiety
roto|plain, field, open area|field||
rotopu|illness, sickness, disease|illness||
runataa|dream, wish, ideal, goal|goal||Refers to a hypothetical reality that one wishes to bring to reality
sebot|break (split)^breaker^object that is broken|break|kebot|Used to denote that the object is broken into large, usually two, pieces
semagro|week of|week|sempaa|Refers to a named, specific week
semali|week (duration)|week|sempaa|
sempaa|week|week||
sered|good, likeable, agreeable|good|serev|
serev|like, be fond of^the one who likes^the one who is liked|like||Can refer to both people and things; when used on people, suggests platonic fondness
seskad|solid|solid||Refers to the solid state of matter
seskom|snow (weather condition)|snow|seskunaa|
seskomaa|snow (substance)|snow||Refers to the snow itself, as opposed to the weather
seskunaa|ice|ice|seskad,kunaa|
set|want, desire, wish^the one who has a desire^the desired thing|want||Can be used as an alternative to the volition inflection if the act of wishing itself needs a description
sibed|hasty, hurried|hasty|sibed|
sibit|hurry, rush^the one hurrying^the action being hurried|hurry||To say "rushed to <destination>", use "erash sibedea", which means "hastily go to"
sinedro|heart of|heart_of||
sinip|rub, wipe^one performing the rubbing^object being rubbed^tool used to rub/substance being rubbed|rub||
sirid|fast, rapid, quick|fast||
sirit|rip, tear^rip, tear^rip|rip||
sokit|cut (with knife)^cutter^object being cut|cut|soku|
soku|knife, blade|knife||
sonal|only|only||
soponu|pain|pain|soku,posku|
sorod|slow|slow||
sud|wrong|wrong|vid|antonym of vid
tato|adult|adult|toto|
tatreto|person|person||May refer to both adults and children
temitaa|mountain, hill|mountain||
tenet|fill, take up space, flood with^the filling substance^the container being filled|fill|tenip|Use "tenip" to denote that the filling agent is not the substance used to fill the container
tenil|currently|currently||Can be used to modify verb infinitives or other forms to indicate the ongoing state of the action
tenip|fill^the one performing the filling^the container being filled^the substance used to fill the container|fill||Use "tenet" to denote that the substance is also the one performing the filling
tesip|press, push, compress^one performing the pressing^object being pressed^surface being pressed against|push||Can also mean "push ... towards ..."
tilit|cut, chop (with axe)^cutter^object being chopped|chop|tilto|
tilto|axe|axe||
tired|uncomfortably hot|hot||Subjectively defined; refers to a temperature that causes discomfort
titolit|kill^the killer^the victim|kill||
todro|child (offspring) of|child|toto|
togedro|tail of|tail_of|tokigro|
tokigro|butt of, buttocks of|butt_of||
tokol|late, near the end of a period of time|late||
tomol|late|late||Refers to an action occuring after the expected time
tomop|postpone, delay^the one postponing^the event being postponed^the time postponed to|postpone||
toseto|hammer|hammer||
tot|hit, strike, beat^hitter^object being hit|hit||
toto|child|child||
tregro|end of|end|trelot|Indicates the end of an action or a period (e.g. season or day)
trelit|begin, start^the one starting an action^the action being started|begin||The slot-2 argument should be a verb in the occurrence inflection; has the same semantics as the transitive/initiation action, so it's used when the initiation itself needs a modifier
trelot|finish, complete^the one finishing up^the action being completed|finish||
trenaa|stone (substance)|stone||
trenataa|statue|statue|trenaa|
tretaa|rock|rock|trenaa|
treted|pleasantly loud|loud||Refers to loudness that is pleasant
trigro|start, beginning of|beginning|trelit|
trolot|stop^the one stopping^the action that is stopped|stop||Does not imply "finish" or "complete", which is handled by "orit"
venedro|sibling of|sibling||
venemo|spring|spring||
veredro|ear of|ear||
veresh|listen to, hear^the listener^the sound being heard|hear|veredro|
vid|correct, right|correct||Used to describe something that conforms to a standard
vidro|lip of|lip_of|buvidro|
vilipu|broom|broom|vilmo|
vilmo|dust|dust||Refers to any fine-grained particles, including ash
vilot|bend^bender^object that is bent|bend||
vogodro|tooth of|tooth_of||Usually refers to a person's complete set of teeth, unless specified using the singular inflection
vogro|midpoint of|midpoint||
volino|midnight, dark night|midnight|vogro,lito|Refers to the time of the day when dusk and dawn are equidistant; to refer to 00:00, use "trigre mika" (beginning of day) instead
voluno|solar noon|noon|vogro,lunaa|Refers to the time of the day when the sun is at the zenith; to refer to 12:00, use "vogro mika" (middle of the day) instead
vomet|wake up, awaken^the waker^the one waking up|wake_up||Use the reflexive inflection to indicate naturally waking oneself up
vomo|soil|soil|vosmaa|
vosedro|foot of, paw of|foot_of||Refers to any body part that normally touches the ground
vosip|bury^the one burying^the object being buried^the location of the burial|bury|vosmaa|
vosmaa|earth, ground|earth||Refers to the ground, not the planet
vosnataa|bay, gulf|bay|vosmaa,kunataa|
vososit|fold^one performing the folding^object being folded|fold||
vosrimaa|fog,mist|fog|vosmaa,lurikaa|
vulot|stretch^stretch^stretch|stretch||
wel|something, someone|something|awelmo|Functionally identical to "awelme"
wil|everything, all|everything|awilmaa|Functionally identical to "awilma"
wol|what|what|awolmaa|Functionally identical to "awolma"
vol|of, pertaining to|of||Links two objects without explicitly stating the nature of the relationship, which is left to the context to decide
konal|another, other|another||
nal|with the name of|named||The following word is the name of the modified object
mel|in, within (abstract)|in||Used to describe being within a timeframe or environment, such as "in the night", "in a week"
deltaa|spot, dot, speck|spot||
sonol|without, lacking|without||Used to modify an object that lacks an association, either through ownership or characteristic, with the following object
liveras|sleep, especially through the night^the sleeper|sleep||
livetu|bed|bed|liveras|
kreskaa|candle|candle|kreskaa|
lipotu|chair|chair||
boltaa|door|door||Both sides are inside a building
mebetaa|gate|gate||At least one side is outside of a building
gelish|live, dwell at^the person living^the location|live_at|gelidro|Refers to residing at a place
vosmu|floor|floor|vosmaa|Refers to any kind of indoor ground, not just wooden floor
domo|house|house||Refers to any kind of dwelling place; comes from the Esperanto word of the same spelling
klitu|key (lock)|key||Refers to the tool used open a lock
gresigro|roof of|roof_of||gremu
kresto|lamp, flashlight, torch, localized lighting|lamp|kreno|
kresito|ceiling light|light|kreno|
klutu|lock|lock|klitu|
imiltaa|room|room||
beletaa|stove, oven, cooking heat source|stove|beledrid|
nonto|table, desk|table||
pulto|wall|wall||
krentu|window|window|kreno|
melmoto|yard, court|yard||
emolkaa|garden|garden||