namespace KrestiaVortilo

module Vortlisto =
   type Vorto =
   | Klaso of string * Animeco : bool * Radikoj : string list * Signifo : string
   | Verbo of string * Valenco : int * Radikoj : string list * Signifo : string
   | Pridiranto of string * Radikoj : string list * Signifo : string

   let listo: Vorto list = [
      Klaso("fosmaa", false, [], "earth (ground)")
      Klaso("lugrismaa", false, [], "earth (landscape)")
      Klaso("kunaa", false, [], "water (positive)")
      Klaso("gonaa", false, [], "water (negative)")
      Klaso("tretaa", false, [], "stone (large bulky)")
      Klaso("sestu", false, [], "stone")
      Klaso("dretu", false, [], "stone (pebble)")
      Klaso("trenaa", false, [], "stone (substance)")
      Klaso("kresku", false, [], "flame (fervidity)")
      Klaso("pospu", false, [], "flame (destructive|")
      Klaso("kresmu", false, [], "fire (fervidity)")
      Klaso("posmu", false, [], "fire (destructive)")
      Klaso("dutaa", false, [], "sand (grain of sand)")
      Klaso("vilto", false, [], "sand (grain of dust)")
      Klaso("dunaa", false, [], "sand (flowing)")
      Klaso("vilmo", false, [], "sand (dust)")
      Klaso("rismo", false, [], "smoke (destructive)")
      Klaso("rinemaa", false, [], "smoke (sign of life)")
      Klaso("ritmaa", false, [], "ash (desolate)")
      Klaso("tretkutaa", false, ["tretaa"; "kunaa"], "ice (large)")
      Klaso("sestutaa", false, ["sestu"; "kunaa"], "ice (ice cube)")
      Klaso("seskonaa", false, ["sestu"; "gonaa"], "ice (cold, desolate)")
      Klaso("skunaa", false, ["kunaa"], "ice (purity, clarity)")
      Klaso("lito", false, [], "night (period)")
      Klaso("lirano", false, [], "night (tranquil)")
      Klaso("rititino", false, [], "night (frightening)")
      Klaso("mikaa", false, [], "daytime (period)")
      Klaso("miginaa", false, [], "daytime")
      Klaso("migimataa", false, [], "year")
      Klaso("migimanaa", false, [], "year")
      Klaso("luvitaa", false, [], "rain (raindrop)")
      Klaso("luvemaa", false, [], "rain")
      Klaso("luveritaa", false, ["luveritmaa"], "cloud (ominous)")
      Klaso("lunevikaa", false, ["luverinemaa"], "cloud")
      Klaso("luveritmaa", false, ["luvemaa"; "ritmaa"], "cloud (ominous)")
      Klaso("luverinemaa", false, ["luvemaa"; "rinemaa"], "cloud")
      Klaso("ritmanaa", false, ["ritmaa"; "skunaa"], "fog")
      Klaso("velitaa", false, [], "wind (breeze)")
      Klaso("geluko", false, [], "wind (gust)")
      Klaso("velino", false, [], "wind (breeze)")
      Klaso("geluno", false, [], "wind")
      Klaso("salumu", false, [], "wind (strong)")
      Klaso("kulemu", false, [], "hurricane")
      Klaso("lustaa", false, [], "star")
      Klaso("lunaa", false, [], "sun")
      Klaso("rimepo", false, [], "moon (satellite)")
      Klaso("rimaa", false, [], "moon (the moon)")
      Klaso("gremu", false, [], "sky")
      Klaso("jamataa", false, [], "mountain")
      Klaso("druretaa", false, [], "road")
      Klaso("drurenaa", false, [], "road (symbol)")
      Klaso("brekaa", false, [], "woods (small)")
      Klaso("bretako", false, [], "woods (vast)")
      Klaso("prismataa", false, [], "lake")
      Klaso("gritaa", false, [], "river (stream)")
      Klaso("pristaa", false, ["prismataa"], "river (creek)")
      Klaso("penataa", false, [], "river")
      Klaso("kunataa", false, ["kunaa"], "sea (small)")
      Klaso("kunagretu", false, ["kunaa"; "gremu"], "sea (vast)")
      Klaso("lukukrestu", false, ["lugrismaa"; "kunaa"; "kresmu"; "sestu"], "body")
      Klaso("alipo", false, [], "head (body)")
      Klaso("kelto", false, [], "shoulder")
      Klaso("relalipo", false, ["rel"; "alipo"], "neck")
      Klaso("gerato", false, [], "hand")
      Klaso("fosmato", false, ["fosmaa"; "gerato"], "foot")
      Klaso("pelano", false, [], "skin")
      Klaso("fosrameko", false, ["fosralato"; "gerameko"], "knee")
      Klaso("fosralato", false, ["fosmato"; "geralato"], "leg")
      Klaso("geralato", false, ["gerato"], "arm")
      Klaso("gerameko", false, ["gerato"], "elbow")
      Klaso("geto", false, ["gerato"], "limb")
      Klaso("gerano", false, ["gerano"], "limbs")
      Klaso("elapo", false, [], "chest")
      Klaso("relelapo", false, ["rel"; "elapo"], "belly")
      Klaso("lukumataa", false, ["lukukrestu"; "jamataa"], "back")
      Klaso("kunipu", false, [], "fingernail")
      Klaso("lepitaa", false, [], "cheek")
      Klaso("riretu", false, [], "ear")
      Klaso("mevitaa", false, [], "eye")
      Klaso("prelino", false, [], "hair")
      Klaso("buvipo", false, [], "mouth")
      Klaso("nuketu", false, [], "nose")
      Klaso("buvipeto", false, ["buvito"], "tongue")
      Klaso("buvisko", false, ["buvipo"], "tooth")
      Klaso("buvismo", false, ["buvipo"], "teeth")
      Klaso("lukukunamaa", false, ["lukukrestu"; "kunaa"], "blood")
      Klaso("lukurenaa", false, ["lukukrestu"; "drurenaa"], "blood (ancestry)")
      Klaso("lukuto", false, ["lukukrestu"], "bone")
      Klaso("lukuritaa", false, ["lukukrestu"; "ritmaa"], "bone (symbol of death)")
      Klaso("lukumu", false, ["lukukrestu"], "meat/flesh")
      Klaso("girismo", false, [], "liver")
      Klaso("krestumu", false, [], "guts") ]