name: Testoj

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Agordi .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Ruli la testojn de Krestia vortilo
      run: dotnet test ./KrestiaVortilo.Testo