name: Testoj

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Agordi .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.201
    - name: Ruli la testojn de KrestiaServilo
      run: dotnet test ./KrestiaServilo.Testo
    - name: Ruli la testojn de KrestiaVortaro
      run: dotnet test ./KrestiaVortaro.Testo
    - name: Ruli la testojn de KrestiaVortilo
      run: dotnet test ./KrestiaVortilo.Testo