name: NuGet package

on:
  release:
    types:
      - created

jobs: 
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.201
      - name: Publish NuGet package
        uses: brandedoutcast/publish-nuget@v2.5.5
        with:
          PROJECT_FILE_PATH: KrestiaVortilo/KrestiaVortilo.fsproj
          NUGET_KEY: ${{ secrets.GITHUB_TOKEN }}
          NUGET_SOURCE: https://nuget.pkg.github.com/Sam647254
          VERSION_REGEX: ^\s*<PackageVersion>(.*)<\/PackageVersion>\s*$